# Generated by Django 5.2.1 on 2025-05-22 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='item_origin',
        ),
    ]
