# Generated by Django 5.2.1 on 2025-05-23 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('app1', '0002_remove_fooditem_item_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='item_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='item_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='account.user'),
        ),
    ]
