# Generated by Django 5.2.1 on 2025-05-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_fooditem_item_price_alter_fooditem_item_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='item_owner_user_id',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
