# Generated by Django 5.2.1 on 2025-05-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=150)),
                ('dob', models.DateField()),
                ('food_items', models.JSONField(default={})),
                ('tip', models.IntegerField(blank=True, default=0, max_length=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customer_detail',
            },
        ),
    ]
