# Generated by Django 5.2.1 on 2025-06-11 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(max_length=10, unique=True)),
                ('items', models.JSONField(default={})),
                ('item_total', models.IntegerField(max_length=5)),
                ('gst', models.IntegerField(max_length=5)),
                ('tips', models.IntegerField(max_length=5)),
                ('total_amount', models.IntegerField(max_length=5)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customerdetail')),
            ],
            options={
                'db_table': 'purchase_detail',
            },
        ),
    ]
