# Generated by Django 5.2.1 on 2025-06-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_purchasedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetail',
            name='mob_num',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
