# Generated by Django 5.2.1 on 2025-06-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_passwd',
            field=models.CharField(max_length=290, unique=True),
        ),
    ]
