# Generated by Django 5.2.1 on 2025-08-15 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrecord',
            name='farm_owner',
            field=models.ForeignKey(db_column='farm_owner_id', on_delete=django.db.models.deletion.CASCADE, related_name='customer_details', to='account.customer'),
        ),
    ]
