# Generated by Django 5.2.1 on 2025-08-19 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('dashboard', '0002_alter_addrecord_farm_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='user',
            field=models.ForeignKey(db_column='owner_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reminder_user', to='account.customer'),
        ),
    ]
