# Generated by Django 5.2.1 on 2025-08-25 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('dashboard', '0003_alter_reminder_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='task_logs', to='account.customer')),
            ],
            options={
                'db_table': 'task_logs',
            },
        ),
    ]
