# Generated by Django 5.2.1 on 2025-08-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_tasklog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='worker_id',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
