# Generated by Django 5.2.1 on 2025-08-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_tasklog_worker_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='addrecord',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
