# Generated by Django 5.2.1 on 2025-08-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_addrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='addrecord',
            name='worker_id',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
