# Generated by Django 5.2.1 on 2025-08-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='worker_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='worker',
            name='worker_role',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
