# Generated by Django 5.2.1 on 2025-07-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user_id',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
