# Generated by Django 5.2.1 on 2025-08-26 16:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_worker_worker_name_worker_worker_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
