# Generated by Django 5.2.1 on 2025-08-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_worker_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='role',
            field=models.CharField(default='owner', max_length=50),
        ),
    ]
